apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: ca-bundle  # The bundle name will also be used for the target
spec:
  sources:
  # Include a bundle of publicly trusted certificates which can be
  # used to validate most TLS certificates on the internet, such as
  # those issued by Let's Encrypt, Google, Amazon and others.
  - useDefaultCAs: true

  # Do this if possible
  # - inLine: |
  #     -----BEGIN CERTIFICATE-----
  #     your root cert here (not base64 encoded).
  #     -----END CERTIFICATE-----

  # A ConfigMap in the "trust" namespace; see "Trust Namespace" below for further details
#  - configMap:
#      name: "step-certificates-certs"
#      key: "root_ca.crt"
  
  target:
    # Sync the bundle to a ConfigMap called `my-org.com` in every namespace which
    # has the label "linkerd.io/inject=enabled"
    # All ConfigMaps will include a PEM-formatted bundle, here named "root-certs.pem"
    # and in this case we also request binary formatted bundles in JKS and PKCS#12 formats,
    # here named "bundle.jks" and "bundle.p12".
    configMap:
      key: "root-certs.pem"
    additionalFormats:
      jks:
        key: "bundle.jks"
      pkcs12:
        key: "bundle.p12"
    namespaceSelector: {} # Without a namespace selector, it will be installed in all namespaces
    #  matchLabels:
    #    linkerd.io/inject: "enabled"
