---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secrets
  namespace: postgresql
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: postgresql-admin-password,password,postgresql-replication-password
    secret-generator.v1.mittwald.de/length: "16"
