---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-seed-secrets
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: redis-password,postgresql-admin-password,password,postgresql-replication-password
    secret-generator.v1.mittwald.de/length: "16"
stringData:
  admin-user: admin
