---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secrets
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: mariadb-root-password,mariadb-replication-password,mariadb-password
    secret-generator.v1.mittwald.de/length: "20"

