---
# I am using this with opnsense and bind.
# This is the "easiest" method but I recommend creating a dedicated key.
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-rfc2136
stringData:
  dns-server: 192.168.0.1
  zone: home.local
  tsig-alg: hmac-sha512
  tsig-key-name: rndc-key
  tsig-secret: secret-key-here