---
ingress:
  enabled: true
  className: "nginx"
  pathtype: ImplementationSpecific
  annotations:
    # kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    external-dns.alpha.kubernetes.io/hostname: "kibana.home.local"
    cert-manager.io/issuer-group: certmanager.step.sm
    cert-manager.io/issuer-kind: StepClusterIssuer
    cert-manager.io/issuer: step-cluster-issuer
  hosts:
    - host: kibana.home.local
      paths:
        - path: /
  tls:
    - secretName: kibana.home.local-tls
      hosts:
        - kibana.home.local
